### PR TITLE
add behaviour for complex properties

### PR DESCRIPTION
**Pull request by gugadev**
This PR allows you to add complex properties like objects and arrays directly into the custom element as any React component. I've made a small refactor too.

Thanks.

### CODE REVIEW

**Comment by gugadev** [comment]
@calebdwilliams hi there. This PR has one caveat with web components built with LitElement: you must implement a converter because in the first render the pragma pass the JSON/Array as is and the component will throw an Error.

To avoid this, just need to provide a custom converter:

```typescript
const converter = {
  fromAttribute: val => {
    try {
      return JSON.parse(val)
    } catch (o_O) {
      return {}
    }
  },
  toAttribute: val => JSON.stringify(val)
}

...

@property({ type: Array, converter }) data: []string = []
```
Pretty simple. Depends of your criteria accept this PR.

Thanks!

**Review by calebdwilliams — COMMENTED** [review]
Hey @gugadev, I'm happy to add this feature to this library, but would you mind providing a sample on how it should be used (documentation in the README) and writing tests here?

I want to take care that this package has minimal impact on any library that might consume it.

**Comment by gugadev** [comment]
> Hey @gugadev, I'm happy to add this feature to this library, but would you mind providing a sample on how it should be used (documentation in the README) and writing tests here?
> 
> I want to take care that this package has minimal impact on any library that might consume it.

Sure, @calebdwilliams ! I'll do that this week!

**Comment by calebdwilliams** [comment]
Just wanted to check in on this.

**Comment by gugadev** [comment]
@calebdwilliams I'm working on this 😄 I modify the PR to fix a small bug and send it again with the tests in a couple of days.

**Comment by calebdwilliams** [comment]
Any update on this PR?

**Comment by gugadev** [comment]
@calebdwilliams Yep, it is almost ready. Sorry for the delay, I'm a little bus 😄 

I'm going to send the PR this weekend! 🎈

**Comment by calebdwilliams** [comment]
Hey @gugadev, any update on this one?

**Comment by calebdwilliams** [comment]
Hey @gugadev, since I haven't seen any movement on this I'm going to close the PR. If you have the chance to get back to it, I'd be more than happy to add it.

**Comment by calebdwilliams** [comment]
@gugadev, just to let you know if you are still looking for this feature, I finally got around to writing [`react-bind-properties`](https://www.npmjs.com/package/react-bind-properties).

**Pull request closed without merging**
